name: Update
description: Incorporate a changelog.yaml into a complete CHANGELOG.md
inputs:
  changelog:
    description: Path to changelog.yaml
    required: false
    default: changelog.yaml
  md:
    description: Path to CHANGELOG.md to update
    required: false
    default: CHANGELOG.md
  version:
    description: Version to stamp in the changelog section header (no version header if omitted)
    required: false
    default: ""
  date:
    description: Date to stamp in the changelog section header, in YYYY-MM-DD format. Defaults to the current time if unspecified.
    required: false
runs:
  using: docker
  image: ../Dockerfile
  args:
    - --changelog
    - ${{ inputs.changelog }}
    - update-changelog
    - --md
    - ${{ inputs.md }}
    - --version
    - ${{ inputs.version }}
    - --date
    - ${{ inputs.date }}
